name: Build with Gradle

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout/releases
      - name: Check out Git repository
        uses: actions/checkout@v4.1.6

      # https://github.com/actions/setup-java/releases
      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew shadowJar --no-daemon

      # https://github.com/actions/upload-artifact/releases
      - name: Upload build artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: UltraCosmetics-gui-addon-dev
          path: build/libs/UltraCosmetics-gui-addon-*-all.jar
