name: Java CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4.1.2 # https://github.com/actions/checkout/releases
      - name: Set up JDK 8
        uses: actions/setup-java@v4.2.1 # https://github.com/actions/setup-java/releases
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Build with Gradle
        run: ./gradlew shadowJar --no-daemon
      - name: Upload build artifact
        uses: actions/upload-artifact@v4.3.2 # https://github.com/actions/upload-artifact/releases
        with:
          name: UltraCosmetics-gui-addon-dev
          path: build/libs/UltraCosmetics-gui-addon-*-all.jar